dataosphere:
  target: ci
  outputs:
    ci:
      type: snowflake
      account: "{{ env_var('SF_ACCOUNT') }}"
      user: "{{ env_var('SF_USER')  }}"
      password: "{{ env_var('SF_PASSWORD') }}"

      role: "{{ env_var('SF_ROLE', 'TRANSFORMER_ROLE') }}"
      warehouse: "{{ env_var('SF_WAREHOUSE', 'COMPUTE_WH') }}"
      database: "{{ env_var('SF_DATABASE', 'DATAOSPHEREINC') }}"

      schema: "{{ env_var('SF_SCHEMA', 'DBT_CI') }}"

      # Sensible defaults
      threads: 4
      client_session_keep_alive: false
      query_tag: "dbt_ci"
