dataosphere:

  target: ci
  outputs:
    ci:
      type: snowflake
      account: "{{ env_var('SF_ACCOUNT') }}"
      user: "{{ env_var('SF_USER')  }}"

      role: "{{ env_var('SF_ROLE', 'SYSADMIN') }}"
      warehouse: "{{ env_var('SF_WAREHOUSE', 'COMPUTE_WH') }}"
      database: "{{ env_var('SF_DATABASE', 'DATAOSPHEREINC') }}"

      schema: "{{ env_var('SF_SCHEMA', 'DBT_CI') }}"
      private_key_path: "{{ env_var('SF_P8_KEY_PATH') }}"

      authenticator: "snowflake_jwt"

      # Sensible defaults
      threads: 4
      client_session_keep_alive: false
      query_tag: "dbt_ci"
