name: "dataosphere"
version: "1.0.0"
config-version: 2

profile: "dataosphere"


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]


target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"


vars:
  wash_project: true
  wash_event_lookback_days: 30
  wash_load_lookback_days: 7

snapshots:
  dataosphere:
    +schema: snapshots
    +tags: ["snapshot", "wash", "kobo"]


models:
  dataosphere:
    # Global defaults
    +persist_docs:
      relation: true
      columns: true
    +tags: ["wash", "kobo"]

    staging:
      +materialized: view
      +schema: stage
      +tags: ["staging"]

    intermediate:
      +materialized: view
      +schema: intermediate
      +tags: ["intermediate"]

    marts:
      +schema: marts
      +tags: ["mart"]

      dimensions:
        +materialized: table
        +schema: marts
        +tags: ["dim"]

      facts:
        +materialized: table
        +schema: marts
        +tags: ["fact"]

    monitoring:
      +materialized: table
      +schema: monitoring
      +tags: ["monitoring"]


tests:
  dataosphere:
    +store_failures: true
    +schema: dbt_test__audit
    +severity: error

